version: '3'

services:
  kafka-1:
    image: docker.pkg.github.com/hanwha-yeonji/kafka/kafka:3.0.0
    ports:
      - 19092:9092
      - 19093:9093
    environment:
      - CLUSTER_ID=RuTPVymzR16F2f40eUFmgw
      - BROKER_ID=1
      - ADVERTISED_PORT=19092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
  kafka-2:
    image: docker.pkg.github.com/hanwha-yeonji/kafka/kafka:3.0.0
    ports:
      - 29092:9092
      - 29093:9093
    environment:
      - CLUSTER_ID=RuTPVymzR16F2f40eUFmgw
      - BROKER_ID=2
      - ADVERTISED_PORT=29092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
  kafka-3:
    image: docker.pkg.github.com/hanwha-yeonji/kafka/kafka:3.0.0
    ports:
      - 39092:9092
      - 39093:9093
    environment:
      - CLUSTER_ID=RuTPVymzR16F2f40eUFmgw
      - BROKER_ID=3
      - ADVERTISED_PORT=39092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093